version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  blackbox:
    image: prom/blackbox-exporter
    ports:
      - 9115:9115
