apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: ecommerce
        image: nginx:latest
        volumeMounts:
        - name: static-files
          mountPath: /usr/share/nginx/html
      volumes:
      - name: static-files
        configMap:
          name: ecommerce-html
