name: Deploy E-commerce Static Site

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Running the workflow on the latest Ubuntu runner
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # Checking out the repository to the action

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Using the peaceiris GitHub Actions to deploy to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Using the GitHub token to authenticate deployment
          publish_dir: ./static-site  # Directory containing your static files (index.html, css, js, etc.
          